package no.nav.eux.adresse.oppdatering.service

val ordForUkjent = listOf(
    "ukjent",
    "vet ikke",
    "nn",
    "ikke sikker",
    "usikker",
    "uvisst",
    "ingen anelse",
    "ikke relevant",
    "irrelevant",
    "tom",
    "ingen opplysning",
    "ikke oppgitt",
    "mangler",
    "uavklart",
    "ikke tilgjengelig",
    "n/a",
    "null",
    "blankt",
    "ingen kommentar",
    "vet ikke nå",
    "kommer senere",
    "unknown",
    "don't know",
    "unsure",
    "not sure",
    "undefined",
    "uncertain",
    "no idea",
    "not applicable",
    "irrelevant",
    "empty",
    "no information",
    "not provided",
    "missing",
    "unavailable",
    "n/a",
    "none",
    "not determined",
    "to be decided",
    "to be updated",
    "blank",
    "not recorded",
    "no response",
    "pending",
    "okänd",
    "vet inte",
    "osäker",
    "ingen aning",
    "oavsett",
    "irrelevant",
    "tom",
    "ingen uppgift",
    "ej tillgänglig",
    "saknas",
    "n/a",
    "null",
    "blankt",
    "ingen kommentar",
    "vet ej",
    "kommer senare",
    "inte bestämt",
    "oidentifierad",
    "ukendt",
    "ved ikke",
    "usikker",
    "ingen anelse",
    "uafklaret",
    "ikke relevant",
    "irrelevant",
    "tom",
    "ingen oplysning",
    "ikke angivet",
    "mangler",
    "ikke tilgængelig",
    "n/a",
    "null",
    "blank",
    "ingen kommentar",
    "kommer senere",
    "ikke besluttet",
    "ubestemt",
    "ikke oplyst"
)

val ordForPostboks = listOf(
    "postboks",
    "pb",
    "p.b.",
    "postb.",
    "postbox",
    "po.box",
)