spring:
  main:
    banner-mode: "off"

logging:
  structured:
    format:
      console: logstash

kafka:
  topics:
    eux-rina-document-events-v1: ${KAFKA_TOPICS_EUX_RINA_DOCUMENT_EVENTS_V1}
  bootstrap-servers: ${KAFKA_BROKERS}
  properties:
    security:
      protocol: SSL
    ssl:
      keystore:
        type: PKCS12
        location: ${KAFKA_KEYSTORE_PATH}
        password: ${KAFKA_CREDSTORE_PASSWORD}
      truststore:
        type: PKCS12
        location: ${KAFKA_TRUSTSTORE_PATH}
        password: ${KAFKA_CREDSTORE_PASSWORD}

client:
  id: ${AZURE_APP_CLIENT_ID}
  secret: ${AZURE_APP_CLIENT_SECRET}
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  pdlApi:
    url: ${PDL_API_URL}
    scope: ${PDL_API_SCOPE}
  pdlMottak:
    url: ${PDL_MOTTAK_URL}
    scope: ${PDL_MOTTAK_SCOPE}
  euxRinaApi:
    url: ${EUX_RINA_API_URL}
    scope: ${EUX_RINA_API_SCOPE}
